### ISSUE TITLE
Finetune TinyViT-5M Model at Higher Resolution

### ISSUE THREAD

**Issue by WNjun** [wkcn/TinyViT#3]
Hi, 

I've recently trained a custom TinyViT-5M-22kto1k model and attempted to finetune it from an image resolution of 224 to 384. However, I observed no improvement in the model's performance post finetuning. I'm wondering if this could be due to the limitations of the model's size, or perhaps I might be missing something in my configuration.

Here is the YAML configuration for the model:

```
MODEL:
  NAME: TinyViT-5M-224to384
  TYPE: tiny_vit

  DROP_PATH_RATE: 0.1

  TINY_VIT:
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 2, 4, 5, 10 ]
    WINDOW_SIZES: [ 12, 12, 24, 12 ]
    EMBED_DIMS: [64, 128, 160, 320]

DATA:
  IMG_SIZE: 384

OUTPUT: ./output
SAVE_FREQ: 10

TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
  EVAL_BN_WHEN_TRAINING: True
TEST:
  CROP: False

AUG:
  MIXUP: 0.0
  CUTMIX: 0.0
```

Could you please help me identify any potential issues or suggest improvements to enhance the finetuning process?

Thank you for your assistance!
